pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                echo "Cloning repo..."
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Installing dependencies and building the project..."
                dir('auto-deploy') {
                    sh 'ls -la'
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                // Optional: เพิ่มการทดสอบในอนาคต
            }
        }

        stage('Install Firebase CLI') {
            steps {
                echo "Installing Firebase CLI..."
                dir('auto-deploy') {
                    // ติดตั้ง Firebase CLI ในโฟลเดอร์ของโปรเจ็กต์
                    sh 'npm install firebase-tools'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying to Firebase Hosting..."
                dir('auto-deploy') {
                    // ทำการ deploy ไปยัง Firebase Hosting
                    sh "firebase deploy --only hosting:auto-deploy01"
                }
            }
        }
    }

    post {
        success {
            echo "Deployment successful!"
        }
        failure {
            echo "Deployment failed."
        }
    }
}
