pipeline {
    agent any

    environment {
        FIREBASE_PROJECT = 'auto-deploy01'
    }

    stages {
        stage('Clone') {
            steps {
                echo 'Cloning repo...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Installing dependencies and building the project...'
                dir('auto-deploy') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                // Add test commands if applicable, e.g., `npm test`
            }
        }

        stage('Install Firebase CLI') {
            steps {
                echo 'Installing Firebase CLI locally...'
                dir('auto-deploy') {
                    sh 'npm install firebase-tools'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying to Firebase Hosting...'
                dir('auto-deploy') {
                    sh 'firebase deploy --only hosting:$FIREBASE_PROJECT  --token ${FIREBASE_TOKEN}'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment succeeded.'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
